services:
  achievementhq-db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .env.prod:/app/.env.prod

  achievementhq-web:  # Name of the container
    image: ghcr.io/monatemedia/python-django-achievementhq:latest # Image from the GitHub Container Registry
    environment:
      VIRTUAL_HOST: achievementhq.monatemedia.com # Tell nginx-proxy to route traffic based on the service name eg. hello-world.monatemedia.com
      LETSENCRYPT_HOST: achievementhq.monatemedia.com # Enable Let's Encrypt SSL for this domain
      VIRTUAL_PORT: 8000 # Tell nginx-proxy that the container serves on port 8000
    depends_on:
      - db
    volumes:
      - .env.prod:/app/.env.prod
    ports:
      - "8000:8000"

volumes:
  postgres_data:
