services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    volumes:
      - static:/staticfiles
    build:
      context: .
    env_file: 
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  nginx:
    build: ./nginx
    volumes:
      - static:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static: # Define the static volume here
  postgres_data: # Define the postgres_data volume here
