services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  web:
    image: ghcr.io/monatemedia/python-django-achievementhq:latest
    build:
      context: .
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_DEBUG: ${DJANGO_DEBUG}

    volumes:
      - static:/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      
  nginx:
    build: ./nginx
    volumes:
      - static:/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static: # Define the static volume here
  postgres_data: # Define the postgres_data volume here
