name: publish

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/python-django-achievementhq
  TAG: ${{ github.sha }} # Add this line to set the TAG variable

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Enable Debugging Logs
        run: echo "::set-env name=ACTIONS_RUNNER_DEBUG::true"

      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Set up .env Variables
        run: |
          echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> .env
          echo "DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}" >> .env
          echo "ADMIN_USER=${{ secrets.ADMIN_USER }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          echo "FAKE_USER_PASSWORD=${{ secrets.FAKE_USER_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env

      - name: Validate Secrets Injection
        run: |
          for var in DJANGO_ALLOWED_HOSTS DJANGO_DEBUG ADMIN_USER ADMIN_EMAIL ADMIN_PASSWORD FAKE_USER_PASSWORD DB_NAME DB_USER DB_PASSWORD DB_HOST DB_PORT DJANGO_SECRET_KEY; do
            if [ -z "${!var}" ]; then
              echo "Error: $var is missing or empty"
            else
              echo "$var is set"
            fi
          done

      - name: Build and Push Docker Image
        run: |
          echo "Building Docker image with the following parameters:"
          echo "REGISTRY: $REGISTRY"
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "TAG: $TAG"

          # Build the Docker image
          docker build . \
            --build-arg DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} \
            --build-arg DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }} \
            --build-arg DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }} \
            --tag $REGISTRY/$IMAGE_NAME:$TAG
          docker inspect $REGISTRY/$IMAGE_NAME:$TAG | grep DJANGO_SECRET_KEY || echo "DJANGO_SECRET_KEY not found"

          # Push the images
          docker push $REGISTRY/$IMAGE_NAME:$TAG
          docker push $REGISTRY/$IMAGE_NAME:latest
