name: publish

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/python-django-achievementhq
  TAG: ${{ github.sha }}

jobs:
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.PAT }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          echo "Building Docker image with the following parameters:"
          echo "REGISTRY: $REGISTRY"
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "TAG: $TAG"

          # Build the Docker image without unnecessary build args
          docker build -t $REGISTRY/$IMAGE_NAME:$TAG .

      - name: Push Docker Image
        run: |
          # Push the Docker image
          docker push $REGISTRY/$IMAGE_NAME:$TAG

  deploy:
    needs: publish
    name: Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        # check this thread to understand why its needed:
        # <https://stackoverflow.com/a/70447517>
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Debug Environment Variables
        run: env

      - name: Connect and Pull
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} " \
            cd ${{ secrets.WORK_DIR }} && \
            docker compose pull && docker compose up -d \
          "

      - name: cleanup
        run: rm -rf ~/.ssh
